name: Release

on:
  push:
    paths-ignore:
      - ".github/**"
      - ".gitattributes"
      - ".idea/**"
    branches:
      - master
  workflow_dispatch:
    
permissions:
  contents: write
  packages: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          
      - uses: paulhatch/semantic-version@v5.3.0
        id: semver
        with:
          tag_prefix: "v"
          major_pattern: "/^\\[(MAJOR)\\].*/"
          major_regexp_flags: ""
          minor_pattern: "/^\\[(FEAT|UPDATE)\\].*/"
          minor_regexp_flags: ""
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: true
          search_commit_body: true
          enable_prerelease_mode: false
          
      - name: Pack Project
        shell: pwsh
        run: |
          dotnet pack --configuration Release --output ./nupkg /p:Version=${{ steps.semver.outputs.version }}
          
      - name: Create GitHub Release
        id: create-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.version }}
          name: Quasm.CLI ${{ steps.semver.outputs.version_tag }}
          draft: false
          prerelease: false
          
      - name: Upload NuGet Package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: "./nupkg/quasm.${{ steps.semver.outputs.version }}.nupkg"
          asset_name: "quasm.${{ steps.semver.outputs.version }}.nupkg"
          asset_content_type: application/octet-stream